import { Transaction } from '../types'
import { formatDate, formatCurrency } from './formatting'

export const exportToCSV = (transactions: Transaction[], filename: string = 'transactions.csv') => {
  const headers = ['Date', 'Description', 'Category', 'Amount', 'Type']
  const rows = transactions.map((t) => [
    formatDate(t.date),
    t.description,
    t.category,
    formatCurrency(t.amount),
    t.type.toUpperCase(),
  ])

  const csv = [
    headers.join(','),
    ...rows.map((row) => row.map((cell) => `"${cell}"`).join(',')),
  ].join('\n')

  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const link = document.createElement('a')
  const url = URL.createObjectURL(blob)

  link.setAttribute('href', url)
  link.setAttribute('download', filename)
  link.style.visibility = 'hidden'

  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

export const exportToJSON = (transactions: Transaction[], filename: string = 'transactions.json') => {
  const data = {
    exportedAt: new Date().toISOString(),
    totalTransactions: transactions.length,
    transactions,
  }

  const json = JSON.stringify(data, null, 2)
  const blob = new Blob([json], { type: 'application/json;charset=utf-8;' })
  const link = document.createElement('a')
  const url = URL.createObjectURL(blob)

  link.setAttribute('href', url)
  link.setAttribute('download', filename)
  link.style.visibility = 'hidden'

  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

export const exportToHTML = (
  transactions: Transaction[],
  metrics: any,
  filename: string = 'financial-report.html'
) => {
  const totalIncome = transactions
    .filter((t) => t.type === 'income')
    .reduce((sum, t) => sum + t.amount, 0)

  const totalExpenses = transactions
    .filter((t) => t.type === 'expense')
    .reduce((sum, t) => sum + t.amount, 0)

  const html = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Financial Report</title>
      <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; }
        h1 { color: #171717; }
        .summary { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px; margin: 20px 0; }
        .card { background: #f5f5f5; padding: 20px; border-radius: 8px; }
        .card h3 { margin: 0 0 10px 0; color: #525252; font-size: 14px; }
        .card .value { font-size: 24px; font-weight: bold; color: #171717; }
        table { width: 100%; border-collapse: collapse; margin-top: 30px; }
        th { background: #f5f5f5; padding: 12px; text-align: left; font-weight: 600; }
        td { padding: 12px; border-bottom: 1px solid #e5e5e5; }
        tr:hover { background: #fafafa; }
        .income { color: #10b981; }
        .expense { color: #171717; }
        .footer { margin-top: 40px; color: #a3a3a3; font-size: 12px; }
      </style>
    </head>
    <body>
      <h1>Financial Report</h1>
      <p>Generated on ${new Date().toLocaleString()}</p>

      <div class="summary">
        <div class="card">
          <h3>Total Income</h3>
          <div class="value income">+${formatCurrency(totalIncome)}</div>
        </div>
        <div class="card">
          <h3>Total Expenses</h3>
          <div class="value expense">-${formatCurrency(totalExpenses)}</div>
        </div>
        <div class="card">
          <h3>Net Balance</h3>
          <div class="value">${formatCurrency(totalIncome - totalExpenses)}</div>
        </div>
      </div>

      <h2>Transaction Details</h2>
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Description</th>
            <th>Category</th>
            <th>Amount</th>
            <th>Type</th>
          </tr>
        </thead>
        <tbody>
          ${transactions
            .map(
              (t) => `
            <tr>
              <td>${formatDate(t.date)}</td>
              <td>${t.description}</td>
              <td>${t.category}</td>
              <td class="${t.type === 'income' ? 'income' : 'expense'}">
                ${t.type === 'income' ? '+' : '-'}${formatCurrency(t.amount)}
              </td>
              <td>${t.type.toUpperCase()}</td>
            </tr>
          `
            )
            .join('')}
        </tbody>
      </table>

      <div class="footer">
        <p>This report was generated by Finance Dashboard.</p>
      </div>
    </body>
    </html>
  `

  const blob = new Blob([html], { type: 'text/html;charset=utf-8;' })
  const link = document.createElement('a')
  const url = URL.createObjectURL(blob)

  link.setAttribute('href', url)
  link.setAttribute('download', filename)
  link.style.visibility = 'hidden'

  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

export const importFromJSON = (file: File): Promise<Transaction[]> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()

    reader.onload = (event) => {
      try {
        const content = event.target?.result as string
        const data = JSON.parse(content)
        const transactions = Array.isArray(data.transactions) ? data.transactions : []
        resolve(transactions)
      } catch (error) {
        reject(new Error('Invalid JSON file format'))
      }
    }

    reader.onerror = () => {
      reject(new Error('Failed to read file'))
    }

    reader.readAsText(file)
  })
}
